## reference: https://docs.travis-ci.com/user/languages/r/

language: r

r: bioc-release

cache: packages

r_github_packages:
  - nolanlab/Rclusterpp
    
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
